const path = require('path');

const languageMap = {
  '.js': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.jsx': 'javascript',
  '.html': 'html',
  '.htm': 'html',
  '.css': 'css',
  '.scss': 'scss',
  '.less': 'less',
  '.json': 'json',
  '.py': 'python',
  '.pyw': 'python',
  '.java': 'java',
  '.cpp': 'cpp',
  '.cxx': 'cpp',
  '.cc': 'cpp',
  '.c': 'c',
  '.h': 'c',
  '.go': 'go',
  '.rs': 'rust',
  '.rb': 'ruby',
  '.php': 'php',
  '.swift': 'swift',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.sql': 'sql',
  '.sh': 'bash',
  '.bash': 'bash',
  '.zsh': 'bash',
  '.ps1': 'powershell',
  '.bat': 'batch',
  '.cmd': 'batch',
  '.md': 'markdown',
  '.mdx': 'markdown',
  '.xml': 'xml',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.toml': 'toml',
  '.ini': 'ini',
  '.cfg': 'ini',
  '.env': 'plaintext',
  '.txt': 'plaintext',
  '.log': 'plaintext',
  '.vue': 'html',
  '.svelte': 'html',
  '.astro': 'html',
  '.lua': 'lua',
  '.r': 'r',
  '.dart': 'dart',
  '.dockerfile': 'dockerfile',
  '.graphql': 'graphql',
  '.gql': 'graphql',
};

const languageColors = {
  javascript: '#f7df1e',
  typescript: '#3178c6',
  html: '#e34f26',
  css: '#1572b6',
  scss: '#cc6699',
  less: '#1d365d',
  json: '#292929',
  python: '#3776ab',
  java: '#b07219',
  cpp: '#f34b7d',
  c: '#555555',
  go: '#00add8',
  rust: '#dea584',
  ruby: '#701516',
  php: '#4f5d95',
  swift: '#f05138',
  kotlin: '#7f52ff',
  sql: '#e38c00',
  bash: '#4eaa25',
  powershell: '#012456',
  batch: '#4eaa25',
  markdown: '#083fa1',
  xml: '#0060ac',
  yaml: '#cb171e',
  toml: '#9c4221',
  ini: '#555555',
  plaintext: '#6b7280',
  lua: '#000080',
  r: '#276dc3',
  dart: '#00b4ab',
  dockerfile: '#384d54',
  graphql: '#e10098',
};

function getLanguage(filename) {
  const ext = path.extname(filename).toLowerCase();
  return languageMap[ext] || 'plaintext';
}

function getLanguageColor(lang) {
  return languageColors[lang] || '#6b7280';
}

module.exports = { getLanguage, getLanguageColor };